<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQIfWjAw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQIfWjAw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQIfWjAw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQIfWjAw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQIfWjAw\App_KernelDevDebugContainer([
    'container.build_hash' => 'QIfWjAw',
    'container.build_id' => 'a1b0ee5c',
    'container.build_time' => 1688920434,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQIfWjAw');
